Loading of the config file and unit tests.
Includes a pre-commit hook for running all unit tests.

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -4,3 +4,8 @@ flake8 . > /tmp/flake8.log || {
     echo "flake8 failed, fix your code! Logs can be found in /tmp/flake8.log"
     exit 1
 }
+
+python -m unittest discover tests/ || {
+    echo "Unit tests failed, fix the errors!"
+    exit 1
+}
